#######################################################################################
# Copyright (C) 2025
# Heiko Amft, DL1BZ (Project deskHPSDR)
#
# All code published unter the GPLv3
#
#######################################################################################
#
# IMPORTANT NOTE:
#
# DO NOT EDIT THIS FILE, use the file make.config.deskhpsdr INSTEAD !
#
#######################################################################################
#
# Default Compile-time options
#
# Copy the following content into the file make.config.deskhpsdr and set the options
# you need or want
#
#######################################################################################

TCI      ?= ON
GPIO     ?= OFF
MIDI     ?= ON
SATURN   ?= OFF
USBOZY   ?= OFF
SOAPYSDR ?= OFF
STEMLAB  ?= OFF
TTS      ?= ON
AUDIO    ?= PULSE
ATU      ?= OFF
COPYMODE ?= OFF
AUTOGAIN ?= OFF
REGION1  ?= OFF
EQ12     ?= OFF
AH4IOB   ?= OFF
DEVEL    ?= OFF
TAHOEFIX ?= ON

#################################################################################################################
#
#  Explanation of compile time options
#
#  TCI          | If ON, compile with TCI support (needs OpenSSL)
#  GPIO         | If ON, compile with GPIO support (RaspPi only, needs libgpiod)
#  MIDI         | If ON, compile with MIDI support
#  TTS          | If ON, compile with TTS support and activate TTS
#  SATURN       | If ON, compile with native SATURN/G2 XDMA support
#  USBOZY       | If ON, deskHPSDR can talk to legacy USB OZY radios (needs  libusb-1.0)
#  SOAPYSDR     | If ON, deskHPSDR can talk to radios supported via SoapySDR-API library
#  STEMLAB      | If ON, deskHPSDR can start SDR app on RedPitay via Web interface (needs libcurl)
#  AUDIO        | If AUDIO=ALSA, use ALSA rather than PulseAudio on Linux (use PulseAudio recommend)
#  ATU          | If ON, acticate some special functions if using an external ATU
#  COPYMODE     | If ON, add some additional copy and restore of settings depend from selected mode
#  AUTOGAIN     | If ON (only if using a Hermes Lite 2 or similar), activate automatic regulation of RxPGA gain
#  REGION1      | If ON, the band borders are set to IARU Region 1, if OFF US frequency borders active
#  EQ12         | If ON, use 12-band EQ instead of 10-band EQ
#  AH4IOB       | If ON, enable support for AH-4 compatible ATU using the Hermes Lite 2 IO board
#  DEVEL        | ONLY FOR INTERNAL DEVELOPER USE AND TESTING ! Leave it ever OFF please !
#  TAHOEFIX     | If ON, a fix for macOS 26 Tahoe will be activated
#
#  If you want to use the Worldmap option (shown as RX panadapter background image instead of the original black
#  filled background) the CPU consumption will be increase !
#  This can be a problem with SoC without enough compute power like the older Raspberry Pi (except Pi5,
#  maybe except Pi4 too). In this case better leave this option OFF !
#
#  If you want to use a non-default compile time option, write them
#  into a file "make.config.deskhpsdr". So, for example, if you want to
#  disable GPIO and have AUDIO=ALSA, create a file make.config.deskhpsdr in
#  the deskhpsdr directory with two lines that read
#
#  GPIO=OFF
#  AUDIO=ALSA
#
#################################################################################################################

-include make.config.deskhpsdr

# get the OS Name
UNAME_S := $(shell uname -s)
CURRDIR := $(shell pwd)
UNAME_R := $(shell uname -r | sed 's/\..*//')
ARCH := $(shell uname -m)

# Desktop directory (Linux may be localized, e.g. "Schreibtisch")
DESKTOP_DIR ?= $(HOME)/Desktop
ifeq ($(UNAME_S),Linux)
DESKTOP_DIR := $(shell command -v xdg-user-dir >/dev/null 2>&1 && xdg-user-dir DESKTOP || echo "$(HOME)/Desktop")
endif

PKG_CONFIG = pkg-config
.DEFAULT_GOAL := all

ifeq ($(UNAME_S), Linux)
WK41 := $(shell $(PKG_CONFIG) --exists webkit2gtk-4.1 && echo yes)
WK40 := $(shell $(PKG_CONFIG) --exists webkit2gtk-4.0 && echo yes)

ifeq ($(WK41),yes)
$(info WebKitGTK 4.1 found, continue...)
else ifeq ($(WK40),yes)
$(info WebKitGTK 4.0 found, continue...)
else
$(info WebKitGTK not found: webkit2gtk-4.1 or webkit2gtk-4.0 are NOT installed, but required now.)
$(info Please install WebKitGTK (webkit2gtk) first!)
$(info Debian Bookworm has package: webkit2gtk-4.0)
$(info Debian Trixie   has package: webkit2gtk-4.1)
$(error Stopping build: install WebKitGTK (e.g. via apt) and retry.)
endif
endif

# Get git commit version and date
GIT_DATE := $(firstword $(shell git --no-pager show --date=short --format="%ai" --name-only))
GIT_VERSION := $(shell git describe --abbrev=0 --tags --always)
GIT_COMMIT := $(shell git log --pretty=format:"%h"  -1)
GIT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null)

#
# Compile with warning level set to maximum. Note the check against "unintendend" fallthroughs
# in switch statements must be requested explicitly.
# Turn off complaints about deprecated functions (new GTK functions are marked deprecated in each
# release) and against unused parameters (those regularly occur in GTK callbacks).
#
ifeq ($(GDB), ON)
	CFLAGS?= -g -O0 -DG_ENABLE_DEBUG
else
	CFLAGS?= -O3
endif

# clang detection (macOS: CC may be "cc" but still clang)
IS_CLANG := $(shell $(CC) --version 2>/dev/null | head -n 1 | grep -qi clang && echo 1 || echo 0)

# clang-only: ensure lrint is emitted as intrinsic (TX-IQ hotpath)
# Apply only to transmitter.o to avoid side-effects in other modules.
ifeq ($(IS_CLANG),1)
  src/transmitter.o: CFLAGS += \
    -fno-math-errno \
	-fno-trapping-math \
	-fdenormal-fp-math=positive-zero
endif

# global compiler directives
CFLAGS += -Wall -Wextra -Wimplicit-fallthrough -Wno-unused-parameter -Wno-deprecated-declarations -Wcast-align
# only for code check
# CFLAGS += -Wstrict-prototypes -Wold-style-definition

# ifneq (,$(findstring arm,$(ARCH)))
# 	CFLAGS += -Wformat=2 -Wshadow -Wpointer-arith -Wcast-qual -Wnull-dereference -Wshorten-64-to-32 -Wvla
# endif
# ifneq (,$(findstring aarch64,$(ARCH)))
# 	CFLAGS += -Wformat=2 -Wshadow -Wpointer-arith -Wcast-qual -Wnull-dereference -Wshorten-64-to-32 -Wvla
# endif

LINK?=$(CC)

ifeq ($(UNAME_S),Darwin)
ifeq ($(shell command -v brew >/dev/null 2>&1 && echo yes),)
$(error Homebrew (brew) is not installed – Please install Homebrew (brew) first !)
endif
BREW_PREFIX := $(shell command -v brew >/dev/null 2>&1 && brew --prefix)
BREW_LIBDIR := $(BREW_PREFIX)/lib
BREW_PCDIR  := $(BREW_LIBDIR)/pkgconfig
BREW_INCDIR := $(BREW_PREFIX)/include
# SDKROOT := $(shell xcrun --sdk macosx --show-sdk-path)
# ARCH_FLAGS := -arch arm64 -arch x86_64
# CFLAGS += -mmacosx-version-min=13.0 $(ARCH_FLAGS) -isysroot $(SDKROOT) -I./src -I/usr/local/include
# LDFLAGS += -mmacosx-version-min=13.0 $(ARCH_FLAGS) -isysroot $(SDKROOT)
# LDFLAGS += -Wl,-rpath,/usr/local/lib
ifneq ($(BREW_PREFIX),)
export PKG_CONFIG_PATH := $(BREW_PCDIR):$(PKG_CONFIG_PATH)
LDFLAGS += -Wl,-rpath,/usr/local/lib -Wl,-rpath,$(BREW_LIBDIR)
endif
# CFLAGS += -mmacosx-version-min=13.0
# LINK   += -mmacosx-version-min=13.0
endif

ifeq ($(UNAME_S),Linux)
LDFLAGS += -Wl,--enable-new-dtags -Wl,-rpath,/usr/local/lib
endif

#
# The "official" way to compile+link with pthreads is now to use the -pthread option
# *both* for the compile and the link step.
#
CFLAGS+=-pthread -I./src
LINK+=-pthread

##############################################################################
# CPP_DEFINES and CPP_SOURCES are "filled" with all  possible options,
# so that everything is processed when running "cppcheck".
##############################################################################

CPP_DEFINES=
CPP_SOURCES=
CPP_INCLUDE=

ifeq ($(UNAME_S),Darwin)
FFTW_CFLAGS := -I$(BREW_INCDIR)
FFTW_LIBS := $(BREW_LIBDIR)/libfftw3.a $(BREW_LIBDIR)/libfftw3f.a
else
FFTW_CFLAGS := $(shell pkg-config --cflags fftw3 fftw3f)
FFTW_LIBS := $(shell pkg-config --libs fftw3 fftw3f)
endif

WDSP_INCLUDE=-I./wdsp-1.29 $(FFTW_CFLAGS)
WDSP_LIBS=wdsp-1.29/libwdsp.a \
          wdsp-libs/lib/librnnoise.a \
		  wdsp-libs/lib/libspecbleach.a \
		  $(FFTW_LIBS)

SOLAR_INCLUDE=-I./libsolar
SOLAR_LIBS=libsolar/libsolar.a `$(PKG_CONFIG) --libs libcurl libxml-2.0`

TELNET_INCLUDE=-I./libtelnet
TELNET_LIBS=libtelnet/libtelnet.a

##############################################################################
#
# Add support for extended noise reduction
#
##############################################################################

CPP_INCLUDE +=$(WDSP_INCLUDE)
CPP_INCLUDE +=$(SOLAR_INCLUDE)
CPP_INCLUDE +=$(TELNET_INCLUDE)

##############################################################################
#
# Settings for optional features, to be requested by un-commenting lines above
#
##############################################################################

##############################################################################
#
# disable GPIO and SATURN for MacOS, simply because it is not there
#
##############################################################################

ifeq ($(UNAME_S), Darwin)
override GPIO    := OFF
override SATURN  := OFF
override WAYLAND := OFF
endif

ifeq ($(UNAME_S), Linux)
GPIOD_VERSION := $(shell pkg-config --modversion libgpiod 2>/dev/null)
GPIOD_MAJOR := $(word 1,$(subst ., ,$(GPIOD_VERSION)))

ifeq ($(GPIOD_MAJOR),2)
override GPIO := OFF
$(info libgpiod V2 detected. This is not supported, disable GPIO support...)
endif

ifeq ($(GPIO),ON)
ifeq ($(GPIOD_MAJOR),1)
$(info libgpiod V1 detected. Compile with GPIO support)
else
override GPIO := OFF
endif
endif

endif

##############################################################################
#
# Add modules for MIDI if requested.
# Note these are different for Linux/MacOS
#
##############################################################################

ifeq ($(UNAME_S),Darwin)
override MIDI := ON
endif
ifeq ($(MIDI),ON)
MIDI_OPTIONS=-DMIDI
MIDI_HEADERS= src/midi_layer.h src/midi_menu.h src/alsa_midi.h
ifeq ($(UNAME_S), Darwin)
MIDI_SOURCES= src/mac_midi.c src/midi2.c src/midi3.c src/midi_menu.c
MIDI_OBJS= src/mac_midi.o src/midi2.o src/midi3.o src/midi_menu.o
MIDI_LIBS= -framework CoreMIDI -framework Foundation
endif
ifeq ($(UNAME_S), Linux)
MIDI_SOURCES= src/alsa_midi.c src/midi2.c src/midi3.c src/midi_menu.c
MIDI_OBJS= src/alsa_midi.o src/midi2.o src/midi3.o src/midi_menu.o
MIDI_LIBS= -lasound
endif
endif
CPP_DEFINES += -DMIDI
CPP_SOURCES += src/mac_midi.c src/midi2.c src/midi3.c src/midi_menu.c
CPP_SOURCES += src/alsa_midi.c src/midi2.c src/midi3.c src/midi_menu.c


##############################################################################
#
# Stuff for text-to-speech, if requested
#
##############################################################################

ifeq ($(TTS),ON)
TTS_OPTIONS=-DTTS
TTS_HEADERS= src/tts.h src/MacTTS.h
ifeq ($(UNAME_S), Darwin)
TTS_SOURCES= src/tts.c src/MacTTS.m
TTS_OBJS= src/tts.o src/MacTTS.o
TTS_LIBS= -framework Foundation -framework AVFoundation
endif
ifeq ($(UNAME_S), Linux)
TTS_OPTIONS=-DTTS
TTS_HEADERS= src/tts.h src/MacTTS.h
TTS_SOURCES= src/tts.c
TTS_OBJS= src/tts.o
endif
endif
CPP_DEFINES += -DTTS
CPP_SOURCES += src/tts.c

##############################################################################
#
# Add libraries for Saturn support, if requested
#
##############################################################################

ifeq ($(SATURN),ON)
SATURN_OPTIONS=-DSATURN
SATURN_SOURCES= \
src/saturndrivers.c \
src/saturnregisters.c \
src/saturnserver.c \
src/saturnmain.c \
src/saturn_menu.c
SATURN_HEADERS= \
src/saturndrivers.h \
src/saturnregisters.h \
src/saturnserver.h \
src/saturnmain.h \
src/saturn_menu.h
SATURN_OBJS= \
src/saturndrivers.o \
src/saturnregisters.o \
src/saturnserver.o \
src/saturnmain.o \
src/saturn_menu.o
endif
CPP_DEFINES += -DSATURN
CPP_SOURCES += src/saturndrivers.c  src/saturnregisters.c src/saturnserver.c
CPP_SOURCES += src/saturnmain.c src/saturn_menu.c


##############################################################################
#
# Add libraries for USB OZY support, if requested
#
##############################################################################

ifeq ($(USBOZY),ON)
USBOZY_OPTIONS=-DUSBOZY
USBOZY_INCLUDE=`$(PKG_CONFIG) --cflags libusb-1.0`
USBOZY_LIBS=`$(PKG_CONFIG) --libs libusb-1.0`
USBOZY_SOURCES= \
src/ozyio.c
USBOZY_HEADERS= \
src/ozyio.h
USBOZY_OBJS= \
src/ozyio.o
endif
CPP_DEFINES += -DUSBOZY
CPP_SOURCES += src/ozyio.c
CPP_INCLUDE += `$(PKG_CONFIG) --cflags libusb-1.0`

##############################################################################
#
# Add libraries for SoapySDR support, if requested
#
##############################################################################

ifeq ($(SOAPYSDR),ON)
SOAPYSDR_OPTIONS=-DSOAPYSDR
ifeq ($(UNAME_S), Darwin)
SOAPYSDR_LIBS=`$(PKG_CONFIG) --libs soapysdr`
SOAPYSDR_INCLUDE=`$(PKG_CONFIG) --cflags soapysdr`
else
SOAPYSDR_INCLUDE= -I/usr/local/include
SOAPYSDR_LIBS= -L/usr/local/lib -lSoapySDR
endif
SOAPYSDR_SOURCES= \
src/soapy_discovery.c \
src/soapy_protocol.c
SOAPYSDR_HEADERS= \
src/soapy_discovery.h \
src/soapy_protocol.h
SOAPYSDR_OBJS= \
src/soapy_discovery.o \
src/soapy_protocol.o
endif
CPP_DEFINES += -DSOAPYSDR
CPP_SOURCES += src/soapy_discovery.c src/soapy_protocol.c
ifeq ($(UNAME_S), Darwin)
CPP_INCLUDE +=`$(PKG_CONFIG) --cflags soapysdr`
else
CPP_INCLUDE += -I/usr/local/include
endif
##############################################################################
#
# Add libraries for GPIO support, if requested
#
##############################################################################

ifeq ($(GPIO),ON)
GPIO_OPTIONS=-DGPIO
ifeq ($(GPIOD_VERSION),1.2)
GPIO_OPTIONS += -DOLD_GPIOD
endif
GPIO_LIBS=-lgpiod -li2c
endif
CPP_DEFINES += -DGPIO

##############################################################################
#
# Activate code for RedPitaya (Stemlab/Hamlab/plain vanilla), if requested
# This code detects the RedPitaya by its WWW interface and starts the SDR
# application.
# If the RedPitaya auto-starts the SDR application upon system start,
# this option is not needed!
#
##############################################################################

ifeq ($(STEMLAB), ON)
STEMLAB_OPTIONS=-DSTEMLAB_DISCOVERY
STEMLAB_INCLUDE=`$(PKG_CONFIG) --cflags libcurl`
STEMLAB_LIBS=`$(PKG_CONFIG) --libs libcurl`
STEMLAB_SOURCES=src/stemlab_discovery.c
STEMLAB_HEADERS=src/stemlab_discovery.h
STEMLAB_OBJS=src/stemlab_discovery.o
endif
CPP_DEFINES += -DSTEMLAB_DISCOVERY
CPP_SOURCES += src/stemlab_discovery.c
CPP_INCLUDE += `$(PKG_CONFIG) --cflags libcurl`

##############################################################################
#
# Activate additional code
#
##############################################################################

ifeq ($(ATU), ON)
ATU_OPTIONS=-D__HAVEATU__
endif
CPP_DEFINES += -D__HAVEATU__

ifeq ($(COPYMODE), ON)
COPYMODE_OPTIONS=-D__CPYMODE__
endif
CPP_DEFINES += -D__CPYMODE__

ifeq ($(AUTOGAIN), ON)
AUTOGAIN_OPTIONS=-D__AUTOG__
endif
CPP_DEFINES += -D__AUTOG__

ifeq ($(DEVEL), ON)
DEVEL_OPTIONS=-D__DVL__
endif
CPP_DEFINES += -D__DVL__

ifeq ($(REGION1), ON)
REG1_OPTIONS=-D__REG1__
endif
CPP_DEFINES += -D__REG1__

ifeq ($(EQ12), ON)
EQ12_OPTIONS=-D__EQ12__
endif
CPP_DEFINES += -D__EQ12__

ifeq ($(AH4IOB), ON)
AH4IOB_OPTIONS=-D__AH4IOB__
endif
CPP_DEFINES += -D__AH4IOB__

# if OS is Linux, but TAHOEFIX is set, remove this
ifeq ($(UNAME_S), Linux)
override TAHOEFIX := OFF
endif

# only if using macOS 26 Tahoe, fix a SDR detection issue
ifeq ($(TAHOEFIX), ON)
TAHOEFIX_OPTIONS=-D__TAHOEFIX__
endif
CPP_DEFINES += -D__TAHOEFIX__

ifeq ($(WAYLAND), ON)
WAYLAND_OPTIONS=-D__WAYLAND__
endif
CPP_DEFINES += -D__WAYLAND__

##############################################################################
#
# Options for audio module
#  - MacOS: only PORTAUDIO
#  - Linux: either PULSEAUDIO (default) or ALSA (upon request)
#
##############################################################################

ifeq ($(UNAME_S), Darwin)
override AUDIO := PORTAUDIO
endif
ifeq ($(UNAME_S), Linux)
  ifneq ($(AUDIO) , ALSA)
    override AUDIO := PULSE
  endif
endif

##############################################################################
#
# Add libraries for using PulseAudio, if requested
#
##############################################################################

ifeq ($(AUDIO), PULSE)
AUDIO_OPTIONS=-DPULSEAUDIO
AUDIO_INCLUDE=
ifeq ($(UNAME_S), Linux)
  AUDIO_LIBS=-lpulse-simple -lpulse -lpulse-mainloop-glib
endif
ifeq ($(UNAME_S), Darwin)
  AUDIO_LIBS=-lpulse-simple -lpulse
endif
AUDIO_SOURCES=src/pulseaudio.c
AUDIO_OBJS=src/pulseaudio.o
endif
CPP_DEFINES += -DPULSEAUDIO
CPP_SOURCES += src/pulseaudio.c

##############################################################################
#
# Add libraries for using ALSA, if requested
#
##############################################################################

ifeq ($(AUDIO), ALSA)
AUDIO_OPTIONS=-DALSA
AUDIO_INCLUDE=
AUDIO_LIBS=-lasound
AUDIO_SOURCES=src/audio.c
AUDIO_OBJS=src/audio.o
endif
CPP_DEFINES += -DALSA
CPP_SOURCES += src/audio.c

##############################################################################
#
# Add libraries for using PortAudio, if requested
#
##############################################################################

ifeq ($(AUDIO), PORTAUDIO)
AUDIO_OPTIONS=-DPORTAUDIO -DPA_USE_COREAUDIO
AUDIO_INCLUDE=`$(PKG_CONFIG) --cflags portaudio-2.0`
AUDIO_LIBS=`$(PKG_CONFIG) --libs portaudio-2.0`
AUDIO_SOURCES=src/portaudio.c
AUDIO_OBJS=src/portaudio.o
endif
CPP_DEFINES += -DPORTAUDIO
CPP_SOURCES += src/portaudio.c
ifeq ($(UNAME_S), Darwin)
# does not exist on RaspPi
CPP_INCLUDE += `$(PKG_CONFIG) --cflags portaudio-2.0`
endif

##############################################################################
#
# Add TCI support, if requested
#
##############################################################################
ifeq ($(TCI), ON)
TCI_OPTIONS=-DTCI
TCI_INCLUDE=`$(PKG_CONFIG) --cflags openssl`
TCI_LIBS=`$(PKG_CONFIG) --libs openssl`
TCI_SOURCES=src/tci.c
TCI_OBJS=src/tci.o
endif
CPP_INCLUDE += `$(PKG_CONFIG) --cflags openssl`
CPP_DEFINES += -DTCI
CPP_SOURCES += src/tci.c

##############################################################################
#
# End of "libraries for optional features" section
#
##############################################################################

##############################################################################
#
# Includes and Libraries for the graphical user interface (GTK)
#
##############################################################################

# ifeq ($(UNAME_S), Linux)
# WEBKIT_PKG := $(shell $(PKG_CONFIG) --exists webkit2gtk-4.1 && echo webkit2gtk-4.1 || echo webkit2gtk-4.0)
# GTK_INCLUDE := $(shell $(PKG_CONFIG) --cflags gtk+-3.0 glib-2.0 gio-2.0 $(WEBKIT_PKG))
# GTK_LIBS    := $(shell $(PKG_CONFIG) --libs   gtk+-3.0 glib-2.0 gio-2.0 $(WEBKIT_PKG))
# endif

# ifeq ($(UNAME_S), Darwin)
# GTK_INCLUDE := $(shell $(PKG_CONFIG) --cflags gtk+-3.0 glib-2.0 gio-2.0)
# GTK_LIBS    := $(shell $(PKG_CONFIG) --libs   gtk+-3.0 glib-2.0 gio-2.0)
# endif

ifeq ($(UNAME_S), Linux)
# WebKit-Version automatisch ermitteln: 4.1 (Trixie) oder Fallback 4.0 (Bookworm)
WEBKIT_PKG := $(shell $(PKG_CONFIG) --exists webkit2gtk-4.1 && echo webkit2gtk-4.1 || echo webkit2gtk-4.0)
GTK_INCLUDE=`$(PKG_CONFIG) --cflags gtk+-3.0 glib-2.0 gio-2.0 $(WEBKIT_PKG)`
GTK_LIBS=`$(PKG_CONFIG) --libs gtk+-3.0 glib-2.0 gio-2.0 $(WEBKIT_PKG)`
endif

ifeq ($(UNAME_S), Darwin)
GTK_INCLUDE=`$(PKG_CONFIG) --cflags gtk+-3.0 glib-2.0 gio-2.0`
GTK_LIBS=`$(PKG_CONFIG) --libs gtk+-3.0 glib-2.0 gio-2.0`
endif

CPP_INCLUDE += $(GTK_INCLUDE)

##############################################################################
#
# Includes and Libraries for JSON-C
#
##############################################################################

JSON_INCLUDE=`$(PKG_CONFIG) --cflags json-c`
JSON_LIBS=`$(PKG_CONFIG) --libs json-c`
CPP_INCLUDE += $(JSON_INCLUDE)

##############################################################################
#
# Specify additional OS-dependent system libraries
#
##############################################################################

ifeq ($(UNAME_S), Linux)
SYS_LIBS=-lrt
endif

ifeq ($(UNAME_S), Darwin)
SYS_LIBS=-framework IOKit -framework Cocoa -framework WebKit
endif

##############################################################################
#
# All the command-line options to compile the *.c files
#
##############################################################################

OPTIONS=$(MIDI_OPTIONS) $(USBOZY_OPTIONS) \
	$(GPIO_OPTIONS) $(SOAPYSDR_OPTIONS) \
	$(ANDROMEDA_OPTIONS) \
	$(SATURN_OPTIONS) \
	$(STEMLAB_OPTIONS) \
	$(TTS_OPTIONS) \
	$(DESKTOP_OPTIONS) \
	$(ATU_OPTIONS) \
	$(COPYMODE_OPTIONS) \
	$(AH4IOB_OPTIONS) \
	$(AUTOGAIN_OPTIONS) \
	$(DEVEL_OPTIONS) \
	$(REG1_OPTIONS) \
	$(EQ12_OPTIONS) \
	$(WAYLAND_OPTIONS) \
	$(TAHOEFIX_OPTIONS) \
	$(AUDIO_OPTIONS) $(TCI_OPTIONS) \
	-DGIT_DATE='"$(GIT_DATE)"' -DGIT_VERSION='"$(GIT_VERSION)"' -DGIT_COMMIT='"$(GIT_COMMIT)"' -DGIT_BRANCH='"$(GIT_BRANCH)"'

INCLUDES=$(GTK_INCLUDE) $(WDSP_INCLUDE) $(SOLAR_INCLUDE) $(TELNET_INCLUDE) $(AUDIO_INCLUDE) $(STEMLAB_INCLUDE) $(TCI_INCLUDE) $(JSON_INCLUDE)
COMPILE=$(CC) $(CFLAGS) $(OPTIONS) $(INCLUDES)

.c.o:
ifeq ($(GDB), ON)
	$(COMPILE) -g -c -o $@ $<
else
	$(COMPILE) -c -o $@ $<
endif

.m.o:
ifeq ($(GDB), ON)
	$(COMPILE) -g -c -o $@ $<
else
	$(COMPILE) -c -o $@ $<
endif

%.o: %.mm
ifeq ($(GDB), ON)
	$(COMPILE) -g -c -o $@ $<
else
	$(COMPILE) -c -o $@ $<
endif

##############################################################################
#
# All the libraries we need to link with (including WDSP, libm, $(SYS_LIBS))
#
##############################################################################

LIBS=	$(AUDIO_LIBS) $(USBOZY_LIBS) $(GTK_LIBS) $(GPIO_LIBS) $(SOAPYSDR_LIBS) $(STEMLAB_LIBS) \
	$(MIDI_LIBS) $(TTS_LIBS) $(TCI_LIBS) $(JSON_LIBS) $(WDSP_LIBS) $(SOLAR_LIBS) $(TELNET_LIBS) -lm $(SYS_LIBS)

##############################################################################
#
# The main target, the deskhpsdr program
#
##############################################################################

PROGRAM=deskhpsdr

##############################################################################
#
# The core *.c files in alphabetical order
#
##############################################################################

SOURCES= \
src/MacOS.c \
src/about_menu.c \
src/actions.c \
src/action_dialog.c \
src/agc_menu.c \
src/ant_menu.c \
src/appearance.c \
src/band.c \
src/band_menu.c \
src/bandstack_menu.c \
src/css.c \
src/configure.c \
src/cw_menu.c \
src/discovered.c \
src/discovery.c \
src/display_menu.c \
src/diversity_menu.c \
src/dxcluster.c \
src/encoder_menu.c \
src/equalizer_menu.c \
src/exit_menu.c \
src/ext.c \
src/extras_menu.c \
src/fft_menu.c \
src/filter.c \
src/filter_menu.c \
src/gpio.c \
src/greyline.c \
src/i2c.c \
src/iambic.c \
src/led.c \
src/main.c \
src/message.c \
src/meter.c \
src/meter_menu.c \
src/mode.c \
src/mode_menu.c \
src/new_discovery.c \
src/new_menu.c \
src/new_protocol.c \
src/noise_menu.c \
src/oc_menu.c \
src/old_discovery.c \
src/old_protocol.c \
src/pa_menu.c \
src/property.c \
src/protocols.c \
src/ps_menu.c \
src/radio.c \
src/radio_menu.c \
src/receiver.c \
src/rigctl.c \
src/rigctl_menu.c \
src/rx_menu.c \
src/rx_panadapter.c \
src/screen_menu.c \
src/sintab.c \
src/sliders.c \
src/startup.c \
src/store.c \
src/store_menu.c \
src/switch_menu.c \
src/toolbar.c \
src/toolbar_menu.c \
src/toolset.c \
src/transmitter.c \
src/tx_menu.c \
src/tx_panadapter.c \
src/version.c \
src/vfo.c \
src/vfo_menu.c \
src/vox.c \
src/vox_menu.c \
src/voice_keyer.c \
src/waterfall.c \
src/xvtr_menu.c \
src/zoompan.c

##############################################################################
#
# The core *.h (header) files in alphabetical order
#
##############################################################################

HEADERS= \
src/MacOS.h \
src/about_menu.h \
src/actions.h \
src/action_dialog.h \
src/adc.h \
src/agc.h \
src/agc_menu.h \
src/alex.h \
src/ant_menu.h \
src/appearance.h \
src/band.h \
src/band_menu.h \
src/bandstack_menu.h \
src/bandstack.h \
src/channel.h \
src/configure.h \
src/css.h \
src/cw_menu.h \
src/dac.h \
src/discovered.h \
src/discovery.h \
src/display_menu.h \
src/diversity_menu.h \
src/dxcluster.h \
src/encoder_menu.h \
src/equalizer_menu.h \
src/exit_menu.h \
src/ext.h \
src/extras_menu.h \
src/fft_menu.h \
src/filter.h \
src/filter_menu.h \
src/gpio.h \
src/greyline.h \
src/iambic.h \
src/i2c.h \
src/led.h \
src/main.h \
src/message.h \
src/meter.h \
src/meter_menu.h \
src/mode.h \
src/mode_menu.h \
src/new_discovery.h \
src/new_menu.h \
src/new_protocol.h \
src/noise_menu.h \
src/oc_menu.h \
src/old_discovery.h \
src/old_protocol.h \
src/pa_menu.h \
src/property.h \
src/protocols.h \
src/ps_menu.h \
src/radio.h \
src/radio_menu.h \
src/receiver.h \
src/rigctl.h \
src/rigctl_menu.h \
src/rx_menu.h \
src/rx_panadapter.h \
src/screen_menu.h \
src/sintab.h \
src/sliders.h \
src/startup.h \
src/store.h \
src/store_menu.h \
src/switch_menu.h \
src/toolbar.h \
src/toolbar_menu.h \
src/toolset.h \
src/transmitter.h \
src/tx_menu.h \
src/tx_panadapter.h \
src/version.h \
src/vfo.h \
src/vfo_menu.h \
src/vox.h \
src/vox_menu.h \
src/voice_keyer.h \
src/waterfall.h \
src/xvtr_menu.h \
src/zoompan.h

##############################################################################
#
# The core *.o (object) files in alphabetical order
#
##############################################################################

OBJS= \
src/MacOS.o \
src/about_menu.o \
src/actions.o \
src/action_dialog.o \
src/agc_menu.o \
src/ant_menu.o \
src/appearance.o \
src/band.o \
src/band_menu.o \
src/bandstack_menu.o \
src/configure.o \
src/css.o \
src/cw_menu.o \
src/discovered.o \
src/discovery.o \
src/display_menu.o \
src/diversity_menu.o \
src/dxcluster.o \
src/encoder_menu.o \
src/equalizer_menu.o \
src/exit_menu.o \
src/ext.o \
src/extras_menu.o \
src/fft_menu.o \
src/filter.o \
src/filter_menu.o \
src/gpio.o \
src/greyline.o \
src/iambic.o \
src/i2c.o \
src/led.o \
src/main.o \
src/message.o \
src/meter.o \
src/meter_menu.o \
src/mode.o \
src/mode_menu.o \
src/new_discovery.o \
src/new_menu.o \
src/new_protocol.o \
src/noise_menu.o \
src/oc_menu.o \
src/old_discovery.o \
src/old_protocol.o \
src/pa_menu.o \
src/property.o \
src/protocols.o \
src/ps_menu.o \
src/radio.o \
src/radio_menu.o \
src/receiver.o \
src/rigctl.o \
src/rigctl_menu.o \
src/rx_menu.o \
src/rx_panadapter.o \
src/screen_menu.o \
src/sintab.o \
src/sliders.o \
src/startup.o \
src/store.o \
src/store_menu.o \
src/switch_menu.o \
src/toolbar.o \
src/toolbar_menu.o \
src/toolset.o \
src/transmitter.o \
src/tx_menu.o \
src/tx_panadapter.o \
src/version.o \
src/vfo.o \
src/vfo_menu.o \
src/vox.o \
src/vox_menu.o \
src/xvtr_menu.o \
src/voice_keyer.o \
src/waterfall.o \
src/zoompan.o

ifeq ($(UNAME_S), Darwin)
	OBJS += src/macos_webview.o
endif

##############################################################################
#
# How to link the program
#
##############################################################################

$(PROGRAM):  $(OBJS) $(AUDIO_OBJS) $(USBOZY_OBJS) $(SOAPYSDR_OBJS) $(TCI_OBJS) \
		$(MIDI_OBJS) $(STEMLAB_OBJS) $(SATURN_OBJS) $(TTS_OBJS)
	$(COMPILE) -c -o src/version.o src/version.c
	$(info Prevent make.config.deskhpsdr: can be changed now.)
	@git update-index --assume-unchanged make.config.deskhpsdr 2>/dev/null || true
	$(info ...continue...)
ifneq (z$(WDSP_INCLUDE), z)
	@+make -C wdsp-1.29
endif
ifneq (z$(SOLAR_INCLUDE), z)
	@+make -C libsolar
endif
ifneq (z$(TELNET_INCLUDE), z)
	@+make -C libtelnet
endif
ifeq ($(UNAME_S),Darwin)
	$(LINK) -headerpad_max_install_names -o $(PROGRAM) $(OBJS) $(AUDIO_OBJS) $(USBOZY_OBJS)  \
		$(SOAPYSDR_OBJS) $(MIDI_OBJS) $(STEMLAB_OBJS) $(SATURN_OBJS) $(TTS_OBJS) \
		$(TCI_OBJS) $(LIBS) $(LDFLAGS)
else
	$(LINK) -o $(PROGRAM) $(OBJS) $(AUDIO_OBJS) $(USBOZY_OBJS) $(SOAPYSDR_OBJS) \
		$(MIDI_OBJS) $(STEMLAB_OBJS) $(SATURN_OBJS) $(TTS_OBJS) \
		$(TCI_OBJS) $(LIBS) $(LDFLAGS)
endif

##############################################################################
#
# "make check" invokes the cppcheck program to do a source-code checking.
#
# The "-pthread" compiler option is not valid for cppcheck and must be filtered out.
# Furthermore, we can add additional options to cppcheck in the variable CPP_OPTIONS
#
# Normally cppcheck complains about variables that could be declared "const".
# Suppress this warning for callback functions because adding "const" would need
# an API change in many cases.
#
# On MacOS, cppcheck usually cannot find the system include files so we suppress any
# warnings therefrom, as well as warnings for functions defined in some
# library but never called.
#
# We want to use the --check-level=exhaustive flag for cppcheck. A sufficiently
# recent version of cppcheck if available on MacOS, and for Debian since
# version 13 "Trixie" which introduced kernel version 6.12
#
##############################################################################

CPP_INCLUDE:=$(shell echo $(CPP_INCLUDE) | sed -e "s/ -pthread/ /" )

CPP_OPTIONS= --inline-suppr --enable=all --suppress=unmatchedSuppression

ifeq ($(UNAME_S), Darwin)
CPP_OPTIONS += -D__APPLE__
CPP_OPTIONS += --check-level=exhaustive
else
CPP_OPTIONS += -D__linux__
CPP_OPTIONS += --suppress=missingIncludeSystem
CPP_OPTIONS += --suppress=unusedFunction
endif

.PHONY:	cppcheck
cppcheck:
	cppcheck $(CPP_OPTIONS) $(CPP_INCLUDE) $(CPP_DEFINES) $(SOURCES) $(CPP_SOURCES)

#############################################################################
#
#  "make clean" delete now all binaries from deskHPSDR, but never the
#  config files in the config-directory
#
#############################################################################

.PHONY:	clean
clean:
	@echo "Cleanup source directory of deskHPSDR..."
	rm -f src/*.o
	rm -f src/*.orig
	rm -f $(PROGRAM) hpsdrsim bootloader
	@if [ -d wdsp-1.29 ]; then $(MAKE) -C wdsp-1.29 clean; fi
	@if [ -d libsolar ]; then $(MAKE) -C libsolar clean; fi
	@if [ -d libtelnet ]; then $(MAKE) -C libtelnet clean; fi
ifeq ($(UNAME_S), Darwin)
	@-rm -rf $(PROGRAM).app
endif
	@echo "DONE."

.PHONY: uninstall mclean
mclean: uninstall
uninstall:
	@echo "Cleanup source directory of deskHPSDR..."
	rm -f src/*.o
	rm -f $(PROGRAM) hpsdrsim bootloader
	@if [ -d wdsp-1.29 ]; then $(MAKE) -C wdsp-1.29 clean; fi
	@if [ -d libsolar ]; then $(MAKE) -C libsolar clean; fi
	@if [ -d libtelnet ]; then $(MAKE) -C libtelnet clean; fi
	@echo "Remove installed deskHPSDR binary..."
ifeq ($(UNAME_S), Darwin)
	@-rm -rf $(PROGRAM).app
	@-rm -fr ${HOME}/Desktop/deskhpsdr.app
else
	@-sudo rm -f /usr/local/bin/$(PROGRAM)
	@-sudo killall rigctld_deskhpsdr || true
	@-sudo rm -f /usr/local/bin/rigctld_deskhpsdr
	@-rm -f ${HOME}/.local/share/applications/deskHPSDR.desktop
	@-rm -f "$(DESKTOP_DIR)"/deskHPSDR.desktop
	@echo "Update Desktop database..."
	@command -v update-database-desktop >/dev/null 2>&1 && update-database-desktop || :
endif
	@echo "DONE."

#############################################################################
#
# hpsdrsim is a cool program that emulates an SDR board with UDP and TCP
# facilities. It even feeds back the TX signal and distorts it, so that
# you can test PureSignal.
# This feature only works if the sample rate is 48000
#
#############################################################################

src/hpsdrsim.o:     src/hpsdrsim.c  src/hpsdrsim.h
	$(CC) -c $(CFLAGS) -o src/hpsdrsim.o src/hpsdrsim.c

src/newhpsdrsim.o:	src/newhpsdrsim.c src/hpsdrsim.h
	$(CC) -c $(CFLAGS) -o src/newhpsdrsim.o src/newhpsdrsim.c

hpsdrsim:       src/hpsdrsim.o src/newhpsdrsim.o
	$(LINK) -o hpsdrsim src/hpsdrsim.o src/newhpsdrsim.o -lm


#############################################################################
#
# bootloader is a small command-line program that allows to
# set the radio's IP address and upload firmware through the
# ancient protocol. This program can only be run as root since
# this protocol requires "sniffing" at the Ethernet adapter
# (this "sniffing" is done via the pcap library)
#
#############################################################################

bootloader:	src/bootloader.c
	$(CC) -o bootloader src/bootloader.c -lpcap

#############################################################################
#
# Create a file named DEPEND containing dependencies, to be added to
# the Makefile. This is done here because we need lots of #defines
# to make it right.
# Since src/MacTTS.c is Objective-C, create the final line manually
#
#############################################################################

.PHONY: DEPEND
DEPEND:
	rm -f DEPEND
	touch DEPEND
	export LC_ALL=C && makedepend -DTCI -DMIDI -DSATURN -DUSBOZY -DSOAPYSDR -DGPIO \
		-DSTEMLAB_DISCOVERY -DPULSEAUDIO \
		-DPORTAUDIO -DALSA -DTTS -D__APPLE__ -D__linux__ \
		-D__HAVEATU__ -D__CPYMODE__ -D__AUTOG__ -D__DVL__ -D__REG1__ \
		-D__EQ12__ -D__WAYLAND__ -D__TAHOEFIX__ -D__AH4IOB__\
		-f DEPEND -I./src src/*.c src/*.h
	echo "src/MacTTS.o: src/message.h" >> DEPEND

#########################################################################################################

#########################################################################################################

.PHONY: prepare

prepare: .WDSP_libs_updated_V3

.WDSP_libs_updated_V3:
	@echo "==> Update WDSP requirements missing → running update_libs.sh"
	@./update_libs.sh

.PHONY: install install-Darwin install-Linux

install: prepare install-$(UNAME_S)

all: prepare $(PROGRAM)

install-Darwin: all
	@echo "Install deskHPSDR for macOS..."
	@make
	@echo "Remove further compiled deskHPSDR..."
	@rm -rf deskHPSDR.app
	@echo "Remove old deskHPSDR.app container from \"$(DESKTOP_DIR)\" ..."
	@rm -rf "$(DESKTOP_DIR)/deskHPSDR.app"
	@mkdir -p deskHPSDR.app/Contents/MacOS
	@mkdir -p deskHPSDR.app/Contents/Frameworks
	@mkdir -p deskHPSDR.app/Contents/Resources
	@echo "Generate macOS deskHPSDR.app container..."
	@cp deskhpsdr deskHPSDR.app/Contents/MacOS/deskhpsdr
	@cp MacOS/PkgInfo deskHPSDR.app/Contents
	@cp MacOS/Info.plist deskHPSDR.app/Contents
	@cp MacOS/hpsdr.icns deskHPSDR.app/Contents/Resources
	@cp MacOS/radio.icns deskHPSDR.app/Contents/Resources
	@if [ -f "${CURRDIR}/MacOS/rigctld_deskhpsdr" ]; then \
		cp "${CURRDIR}/MacOS/rigctld_deskhpsdr" deskHPSDR.app/Contents/Resources; \
	fi
	@echo "Copy additional needed Fonts..."
	@mkdir -p "$(HOME)/Library/Fonts"
	@cp -R fonts/ttf/Roboto "${HOME}/Library/Fonts"
	@cp -R fonts/ttf/JetBrainsMono "${HOME}/Library/Fonts"
	@cp -R fonts/otf/GNU "${HOME}/Library/Fonts"
	@sleep 1
	@echo "Rebuild font cache..."
	@-fc-cache -f
	@sleep 1
	@git update-index --assume-unchanged make.config.deskhpsdr
	@if [ -x /usr/bin/codesign ]; then \
		echo "Strip extended attributes before codesigning..."; \
		xattr -cr deskHPSDR.app; \
		echo "Codesign deskHPSDR against possible problems with gatekeeper..."; \
		codesign --force --deep --sign - deskHPSDR.app; \
		sleep 1; \
		echo "Verify deskHPSDR codesign..."; \
		codesign --verify --deep --strict --verbose=2 deskHPSDR.app; \
	fi
	@echo "Copy deskHPSDR to your Desktop..."
	@mv deskHPSDR.app "$(DESKTOP_DIR)"
	@echo "Starting deskHPSDR..."
	@open -a "$(DESKTOP_DIR)/deskHPSDR.app"

install-Linux: all
	@echo "Install deskHPSDR for Linux..."
	@make
	@sleep 1
	@sudo ldconfig
	@sleep 1
	@echo "Remove previous deskHPSDR binary..."
	@sudo rm -f "/usr/local/bin/$(PROGRAM)"
	@echo "Copy just compiled deskHPSDR binary to /usr/local/bin"
	@sudo install -m 0755 -t /usr/local/bin "$(PROGRAM)"
	@if [ -f "${CURRDIR}/LINUX/rigctld_deskhpsdr" ]; then \
		echo "Copy special rigctld to /usr/local/bin"; \
		sudo install -m 0755 -t /usr/local/bin "${CURRDIR}/LINUX/rigctld_deskhpsdr"; \
	fi
	@if [ -f "${CURRDIR}/LINUX/vcable.sh" ]; then \
		echo "Copy vcable.sh to /usr/local/bin"; \
		sudo install -m 0755 -t /usr/local/bin "${CURRDIR}/LINUX/vcable.sh"; \
	fi
	@echo "Copy icon files for deskHPSDR to /usr/local/share/$(PROGRAM)"
	@sudo mkdir -p "/usr/local/share/$(PROGRAM)"
	@sudo cp release/"$(PROGRAM)"/hpsdr*.png "/usr/local/share/$(PROGRAM)"
	@sudo cp release/"$(PROGRAM)"/trx_icon.png "/usr/local/share/$(PROGRAM)"
	@echo "Copy icon files for deskHPSDR to /usr/local/share/icons"
	@sudo mkdir -p "/usr/local/share/icons"
	@sudo cp release/"$(PROGRAM)"/radio_icon.png "/usr/local/share/icons"
	@sudo cp release/"$(PROGRAM)"/trx_icon.png "/usr/local/share/icons"
	@echo "Copy additional needed Fonts..."
	@if [ -d /usr/share/fonts/truetype ]; then \
		sudo cp -R fonts/ttf/Roboto /usr/share/fonts/truetype; \
		sudo cp -R fonts/ttf/JetBrainsMono /usr/share/fonts/truetype; \
	else \
		mkdir -p "${HOME}/.local/share/fonts/truetype"; \
		cp -R fonts/ttf/Roboto "${HOME}/.local/share/fonts/truetype"; \
		cp -R fonts/ttf/JetBrainsMono "${HOME}/.local/share/fonts/truetype"; \
	fi; \
	if [ -d /usr/share/fonts/opentype ]; then \
		sudo cp -R fonts/otf/GNU /usr/share/fonts/opentype; \
	else \
		mkdir -p "${HOME}/.local/share/fonts/opentype"; \
		cp -R fonts/otf/GNU "${HOME}/.local/share/fonts/opentype"; \
	fi
	@sleep 1
	@echo "Rebuild font cache..."
	@-sudo fc-cache -f
	@echo "Install X11 deskHPSDR desktop file..."
	@-rm -f "${HOME}/.local/share/applications/deskHPSDR.desktop"
	@cp LINUX/deskHPSDR.desktop "${HOME}/.local/share/applications"
	@echo "Create a link for deskHPSDR at the Desktop..."
	@-rm -f "$(DESKTOP_DIR)"/deskHPSDR.desktop
	@cp LINUX/deskHPSDR.desklnk "${CURRDIR}/deskHPSDR.desktop"
	@echo "URL=${HOME}/.local/share/applications/deskHPSDR.desktop" >> "${CURRDIR}/deskHPSDR.desktop"
	@install -m 0755 -t "$(DESKTOP_DIR)" "${CURRDIR}/deskHPSDR.desktop"
	@-rm -f "${CURRDIR}/deskHPSDR.desktop"
	@sudo sync
	@echo "Update Desktop database..."
#	@command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database || :
	@update-desktop-database ~/.local/share/applications >/dev/null 2>&1 || :
	@sleep 1
	@echo "Prevent make.config.deskhpsdr: can be changed now."
	@git update-index --assume-unchanged make.config.deskhpsdr

.PHONY: update
update:
	@+make clean
	@sleep 1
	@echo "Prevent make.config.deskhpsdr: can be changed now."
	@git update-index --assume-unchanged make.config.deskhpsdr
	@echo "Checkout deskHPSDR master branch..."
	@git checkout master
	@sleep 1
	@echo "Update deskHPSDR..."
	@git pull
	@sleep 1
	@echo "Update done."
	@echo "All done."
	@echo "Please recompile deskHPSDR now."
