/* Copyright (C)
* 2015 - John Melton, G0ORX/N6LYT
* 2024,2025 - Heiko Amft, DL1BZ (Project deskHPSDR)
*
*   This source code has been forked and was adapted from piHPSDR by DL1YCF to deskHPSDR in October 2024
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*
*/

#include <gtk/gtk.h>
#include <semaphore.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "actions.h"
#include "controller_mapping.h"
#include "toolbar.h"
#include "mode.h"
#include "filter.h"
#include "bandstack.h"
#include "band.h"
#include "discovered.h"
#include "new_protocol.h"
#include "old_protocol.h"
#include "vfo.h"
#include "agc.h"
#include "channel.h"
#include "radio.h"
#include "receiver.h"
#include "transmitter.h"
#include "property.h"
#include "new_menu.h"
#include "ext.h"
#include "message.h"
#include "main.h"

int function = 0;

static int width;
static int height;
static int requested_height;
static int visible_rows_last;

// static GtkWidget *toolbar = NULL;
enum {
  TOOLBAR_ROWS_MAX = 2,
  TOOLBAR_BUTTONS_PER_ROW = 11,
  TOOLBAR_FIRST_ROW_FUNCTION_COL = TOOLBAR_BUTTONS_PER_ROW - 1,
  TOOLBAR_BUTTON_COUNT = TOOLBAR_ROWS_MAX * TOOLBAR_BUTTONS_PER_ROW,
  GRID_SPAN = 4,
  GRID_COLS = TOOLBAR_BUTTONS_PER_ROW,
  LABEL_LEN = 16
};

static GtkWidget *sim_s[TOOLBAR_BUTTON_COUNT] = { NULL };

SWITCH *toolbar_switches = switches_toolbar[0];

int toolbar_get_visible_rows(int my_width, int my_height) {
  int min_height = (receivers <= 1) ? 720 : 800;
  return (my_width >= 1280 && my_height >= min_height) ? 2 : 1;
}

static gboolean toolbar_is_function_slot(int switch_index) {
  return switch_index == TOOLBAR_FIRST_ROW_FUNCTION_COL;
}

int toolbar_get_height(int my_width, int my_height, int row_height) {
  if (row_height < 1) { row_height = 1; }
  return toolbar_get_visible_rows(my_width, my_height) * row_height;
}

gboolean toolbar_needs_rebuild(int my_width, int my_height, int window_height) {
  return width != my_width || requested_height != my_height ||
         visible_rows_last != toolbar_get_visible_rows(my_width, window_height);
}

static void toolbar_button_label(char *label, size_t label_size, int switch_index) {
  if (toolbar_is_function_slot(switch_index)) {
    snprintf(label, label_size, "FNC(%d)", function);
  } else {
    snprintf(label, label_size, "%s", ActionTable[toolbar_switches[switch_index].switch_function].button_str);
  }
}

static int toolbar_button_action(int switch_index) {
  return toolbar_is_function_slot(switch_index) ? FUNCTION : toolbar_switches[switch_index].switch_function;
}

void update_toolbar_labels(void) {
  if (sim_s[0]) {
    //
    // If the toolbar has not yet been on display,
    // sim_s0 and friends are NULL
    //
    for (int i = 0; i < TOOLBAR_BUTTON_COUNT; i++) {
      if (sim_s[i]) {
        char lbl[LABEL_LEN];
        toolbar_button_label(lbl, sizeof(lbl), i);
        gtk_button_set_label(GTK_BUTTON(sim_s[i]), lbl);
      }
    }
  }
}

// cppcheck-suppress constParameterCallback
static void toolbar_button_press_cb(GtkWidget *widget G_GNUC_UNUSED, GdkEventButton *event, gpointer data) {
  int i = GPOINTER_TO_INT(data);
  //
  // Filter out any special events generated by double or triple clicks
  //
  if (event->type != GDK_BUTTON_PRESS) { return; }
  //
  // This is our "easter egg" for the FUNC toolbar button. A secondary (right) click
  // cycles backwards
  //
  int action = toolbar_button_action(i);
  if (action == FUNCTION && event->button == GDK_BUTTON_SECONDARY) {
    schedule_action(FUNCTIONREV, PRESSED, 0);
  } else {
    schedule_action(action, PRESSED, 0);
  }
}

// cppcheck-suppress constParameterCallback
static void toolbar_button_released_cb(GtkWidget *widget G_GNUC_UNUSED, GdkEventButton *event G_GNUC_UNUSED,
                                       gpointer data) {
  int i = GPOINTER_TO_INT(data);
  //t_print("%s: %d action=%d\n",__func__,i,toolbar_switches[i].switch_function);
  schedule_action(toolbar_button_action(i), RELEASED, 0);
}

GtkWidget *toolbar_init(int my_width, int my_height, int window_height) {
  width = my_width;
  requested_height = my_height;
  int visible_rows = toolbar_get_visible_rows(my_width, window_height);
  visible_rows_last = visible_rows;
  height = my_height;
  if (!full_screen) {
    height -= 10;
  }
  if (height < 1) { height = 1; }
  int row_height = height / visible_rows;
  if (row_height < 1) { row_height = 1; }
  int button_width = MAX(1, width / GRID_COLS);
  const char *button_css = "small_button";
  t_print("toolbar_init: width=%d height=%d rows=%d row_height=%d button_width=%d\n", width, height,
          visible_rows, row_height, button_width);
  t_print("toolbar_init: button_css=%s\n", button_css);
  toolbar_switches = switches_toolbar[function];
  // Sim-State immer beim Neuaufbau zurücksetzen
  for (int i = 0; i < TOOLBAR_BUTTON_COUNT; ++i) {
    sim_s[i] = NULL;
  }
  GtkWidget *toolbar = gtk_grid_new();
  gtk_widget_set_size_request(toolbar, width, height);
#ifdef __linux__
  gtk_widget_set_margin_top(toolbar, 10);
#endif
  gtk_grid_set_column_homogeneous(GTK_GRID(toolbar), TRUE);
  gtk_grid_set_row_homogeneous(GTK_GRID(toolbar), TRUE);
  int col_width = GRID_SPAN;
  for (int row = 0; row < visible_rows; row++) {
    for (int col = 0; col < TOOLBAR_BUTTONS_PER_ROW; col++) {
      int i = row * TOOLBAR_BUTTONS_PER_ROW + col;
      char lbl[LABEL_LEN];
      toolbar_button_label(lbl, sizeof(lbl), i);
      sim_s[i] = gtk_button_new_with_label(lbl);
      g_object_add_weak_pointer(G_OBJECT(sim_s[i]), (gpointer *) &sim_s[i]);
      gtk_widget_set_name(sim_s[i], button_css);
      gtk_widget_set_size_request(sim_s[i], button_width, row_height);
      g_signal_connect(G_OBJECT(sim_s[i]), "button-press-event", G_CALLBACK(toolbar_button_press_cb),
                       GINT_TO_POINTER(i));
      g_signal_connect(G_OBJECT(sim_s[i]), "button-release-event", G_CALLBACK(toolbar_button_released_cb),
                       GINT_TO_POINTER(i));
      gtk_grid_attach(GTK_GRID(toolbar), sim_s[i], col * GRID_SPAN, row, col_width, 1);
    }
  }
  gtk_widget_show_all(toolbar);
  return toolbar;
}
